- scripts/dynamo/load.go
- sources/dynamodb/dynamodb.go
* Modifying reading DynamoDB's change streams
* Jitter-sleep across attempts to not overwhelm the DynamoDB API
* Added a load test script to simulate data
> [DynamoDB] Final touches + adding a load test

- Makefile
So we have an easier way to clean up test results
> Add Make clean.

- lib/dynamo/message.go
- lib/dynamo/message_test.go
Tweaking the `NewMessage(...)` validation and adding tests
> New Message validation

- sources/dynamodb/dynamodb.go
- sources/dynamodb/snapshot.go
Adding logging for:
1. Discoverying data files to process
2. Starting and ending data files
> Adding logging to snapshot

- README.md
> Update Artie Logo

- .github/workflows/gha-go-test.yaml
- Makefile
- config/config.go
- constants/constants.go
- lib/kafkalib/batch.go
- lib/kafkalib/kafka.go
- lib/logger/logger.go
- sources/dynamodb/shard.go
* Addressing errors from `staticchecks`
* Adding `staticcheck` to our GHA to prevent regression
> Addressing staticchecks

- config/config.go
- lib/kafkalib/kafka.go
> [cfg] Allow specifying max request size.

- config/config.go
- config/postgres.go
- config/postgres_test.go
- constants/constants.go
- lib/kafkalib/batch.go
- lib/kafkalib/batch_test.go
- lib/kafkalib/kafka.go
- sources/dynamodb/dynamodb.go
1. Changing all the ints that cannot be negative to `uint`
2. Adding a PostgreSQL config as a step for us to migrate away from `custom-snapshots`
> [Config] Standing up the PostgreSQL config

- lib/mtr/mtr.go
- lib/ttlmap/ttlmap.go
- lib/ttlmap/ttlmap_test.go
- main.go
- sources/dynamodb/dynamodb.go
- sources/dynamodb/offsets/offsets.go
- sources/dynamodb/offsets/offsets_test.go
Also:
- Pass tags and namespace to Datadog client on construction
> Pull context out of dynamodb.Load

- config/config.go
- lib/dynamo/message.go
- lib/kafkalib/batch_test.go
- lib/kafkalib/kafka.go
- lib/kafkalib/message.go
- lib/kafkalib/message_test.go
- Add a function to build a Kafka writer from `config.Kafka`
- Add a reloadable Kafka writer
- Add `NewMessage` function
- Refactor dynamo.KafkaMessage to use `NewMessage`
> Kafka improvements

- lib/jitter.go
- lib/kafkalib/errors.go
- lib/kafkalib/errors_test.go
- lib/kafkalib/kafka.go
- lib/kafkalib/writer.go
From https://github.com/artie-labs/custom-snapshots/pull/76
> Add batch writer

- lib/kafkalib/writer.go
- lib/postgres/iterator.go
Other than changing the package this is identical to https://github.com/artie-labs/custom-snapshots/blob/master/process/table.go
> Add postgres table iterator

- config/config.go
- constants/constants.go
- lib/dynamo/message.go
- lib/kafkalib/batch.go
- lib/kafkalib/kafka.go
- lib/kafkalib/writer.go
- lib/postgres/load.go
- main.go
- sources/dynamodb/dynamodb.go
- sources/dynamodb/shard.go
- sources/dynamodb/snapshot.go
- sources/postgres/snapshot.go
Also moves postgres.Run() to sources/postgres
> Pull config and kafka writer out of context

- lib/postgres/scan.go
Follow up from https://github.com/artie-labs/reader/pull/60, just rename and reorder things, no logic changes.
> Clean up postgres scanner - pt2

- lib/postgres/message.go
- sources/postgres/snapshot.go
Also rename `lib/postgres/iterator.go` to `lib/postgres/message.go`
> Move LoadTable to snapshot.go

- README.md
- examples/dynamodb.yaml
- examples/postgres.yaml
Updating our README with existing capabilities
> Improving README

- config/config.go
- lib/dynamo/message.go
- lib/kafkalib/message.go
- lib/kafkalib/writer.go
- lib/postgres/message.go
- lib/postgres/message_test.go
- lib/types.go
MongoDB snapshots is done: #82, to make it easier to review, I split out non-MongoDB specific changes out so it's easier to review.
> Refactoring Reader prior to MongoDB 

- go.mod
- go.sum
- lib/postgres/config.go
- lib/postgres/debezium/data_type.go
- lib/postgres/parse.go
- lib/postgres/parse_test.go
1. Upgrading Transfer
2. Supporting `Geography`
> [PostGIS] Supporting Geography

- main.go
- sources/dynamodb/dynamodb.go
- sources/dynamodb/shard.go
- sources/dynamodb/snapshot.go
Instead just pass `writer` in the `Run` method.
> Pull Kafka writer out of DynamoDB `Source`

- lib/postgres/columns.go
- lib/postgres/config.go
- lib/postgres/config_test.go
- lib/postgres/parse_test.go
Also rename `UpdateCols` to `AddColumn` and remove the outdated comment for it.
> Split out postgres to debezium conversion

- lib/postgres/columns.go
- lib/postgres/columns_test.go
Test:
- `hstore`
- Geometry
- Geography
- User defined
- Money
- Numeric with scale + precision
> Add more `colKindToDataType` tests

- lib/postgres/primary_key/primary_keys.go
- lib/postgres/table.go
Combined it with `FindStartAndEndPrimaryKeys`.
> [postgres] Kill `findPrimaryKeys`

- lib/postgres/debezium/payload.go
- lib/postgres/debezium/payload_test.go
- lib/postgres/message.go
`NewArgs.Columns` is never read.
> [postgres] Remove unused field

- lib/postgres/columns.go
- lib/postgres/schema/schema.go
- lib/postgres/table.go
No changes to `PopulateColumns`, just moved it.
> [postgres] move `PopulateColumns`

- lib/postgres/scan.go
- lib/postgres/table.go
- lib/postgres/table_test.go
Working on slowly moving away from depending on `Fields`.
> [postgres] Use table columns for types when scanning

- lib/mysql/schema/schema.go
- lib/postgres/schema/schema.go
- lib/postgres/schema/schema_test.go
Also rename MySQL functions so they are similarly named.
> [postgres] Combine functions for fetching primary key values

- lib/postgres/table.go
- sources/mysql/snapshot.go
- sources/postgres/snapshot.go
- sources/postgres/transformer/transformer_test.go
Also made some tiny tweaks to the Postgres snapshot code.
> [mysql] Add snapshot stub

- sources/mysql/adapter/adapter.go
- sources/mysql/adapter/values.go
- sources/postgres/adapter/adapter.go
- sources/postgres/adapter/values.go
- sources/postgres/adapter/values_test.go
Also rename `ParseValue` to `ConvertValueToDebezium`.
> [mysql] Implement `ConvertRowToDebezium` for adapter

- sources/dynamodb/dynamodb.go
- sources/dynamodb/snapshot.go
- sources/dynamodb/stream.go
No code changes at all just relocated methods.
> [dynamodb] Move store methods

- lib/debezium/transformer.go
No need to build the Debezium schema once per payload when it never changes.
> [debezium] Build schema once for transformer

- Makefile
- lib/postgres/cast.go
- sources/postgres/integration_test/main.go
Ran this against [v0.0.25](https://github.com/artie-labs/reader/tags) (with some slight modifications since some of the classes have changed) and it produces the identical output.
> [postgres] Add integration test

- sources/postgres/integration_test/main.go
Ran this against [v0.0.25](https://github.com/artie-labs/reader/tags) (with some slight modifications since some of the classes have changed) and it produces the identical output.
> [postgres] Add scanning integration test

- .github/workflows/gha-integration-tests.yaml
- Makefile
- integration_tests/mysql/main.go
- integration_tests/postgres/main.go
- integration_tests/utils/utils.go
Doesn't actually test anything, that will come in the next PR.
> [mysql] Add integration test scaffolding

- integration_tests/postgres/docker-compose.yaml
- integration_tests/postgres/main.go
- integration_tests/utils/utils.go
- lib/mysql/schema/convert.go
- lib/postgres/cast.go
- lib/postgres/scanner.go
- lib/postgres/scanner_test.go
- sources/mysql/adapter/adapter.go
- sources/mysql/adapter/adapter_test.go
Also:
- Add a `docker-compose.yaml` file
- Test `int` arrays
- Return an error if we try to quote a primary key value that we don't support
> [postgres] Add primary keys integration test

- lib/postgres/scanner.go
- lib/postgres/scanner_test.go
Should merge https://github.com/artie-labs/reader/pull/225 first.
> [postgres] Pull out primary key string conversion logic

- integration_tests/mysql/main.go
- integration_tests/postgres/main.go
- lib/mysql/table.go
- lib/postgres/table.go
- sources/mysql/snapshot.go
- sources/postgres/adapter/transformer_test.go
- sources/postgres/snapshot.go
Combines the `NewTable` and `PopulateColumns` functions into one function: `LoadTable`.
> [mysql,postgres] Load table metadata when initializing

- go.mod
- go.sum
Fix CVE-2024-27304
https://github.com/jackc/pgx/blob/master/CHANGELOG.md#554-march-4-2024
> Bump pgx to `v5.5.4`

- lib/debezium/converters/decimal.go
- lib/debezium/converters/decimal_test.go
- sources/postgres/adapter/adapter.go
- sources/postgres/adapter/fields.go
- sources/postgres/adapter/values.go
- sources/postgres/adapter/values_test.go
Will merge after https://github.com/artie-labs/reader/pull/247 since that PR adds a test that will ensure there aren't any data conversion changes in this PR.
> [postgres] Add `VariableNumericConverter`

- lib/postgres/parse/parse.go
- lib/postgres/schema/schema.go
No code changes, just reordered the cases.
> [postgres] Reorder `ParseValue` cases

- integration_tests/mysql/main.go
- sources/mysql/adapter/adapter.go
- sources/mysql/adapter/adapter_test.go
- sources/mysql/snapshot.go
MySQL topic didn't include the database name
> Fix MySQL Kafka Topic

- integration_tests/mysql/main.go
- lib/mysql/schema/schema.go
- lib/mysql/schema/schema_test.go
This PR adds support for unsigned integers by making them into `int64`, which is what Debezium is doing.
> [MySQL] Support Unsigned integers.

- lib/debezium/transformer/transformer_test.go
- lib/iterator/batch.go
- lib/iterator/batch_test.go
- lib/iterator/iterator.go
- lib/iterator/iterator_test.go
- lib/iterator/slice_test.go
- lib/iterator/types.go
- lib/kafkalib/writer.go
- sources/postgres/adapter/transformer_test.go
Makes testing iterators a lot easier.
> Add `iterator.Collect` function

- lib/kafkalib/errors.go
- lib/kafkalib/errors_test.go
- lib/kafkalib/writer.go
Timeouts can be transient, we should try to retry and re-establish a connection.
> More Retryable Errors

- go.mod
- go.sum
- lib/debezium/converters/decimal.go
- lib/debezium/converters/decimal_test.go
- sources/postgres/adapter/adapter_test.go
- sources/postgres/adapter/converters.go
- sources/postgres/adapter/converters_test.go
Also use the `debezium.DecodeDecimal` function that ships with transfer.
> Upgrade transfer to `v1.22.31`

- integration_tests/mysql/main.go
- integration_tests/postgres/main.go
- lib/logger/logger.go
In https://github.com/artie-labs/transfer/pull/429 I updated the wrong file. :(
> Disable log colors when not using a terminal (redux)

- go.mod
- go.sum
- writers/transfer/writer.go
- Also bump transfer to `v1.22.38`
> [transfer] Call dedupe on complete

- writers/transfer/writer.go
Also log how long dedupes take.
> [transfer] Fix panic in `Writer.Dedupe`

- go.mod
- go.sum
> Upgrade Artie Transfer dependency

- go.mod
- go.sum
so we can use the new dedupe method
> Upgrade Artie Transfer.

- writers/transfer/writer.go
- writers/transfer/writer_test.go
Getting the primary key for MongoDB is special, we were not using the method we implemented in Transfer, so this was failing.
> [Snapshot] Fix MongoDB

- go.mod
- go.sum
> Upgrade Artie Transfer

- lib/kafkalib/errors.go
- lib/kafkalib/errors_test.go
No errors in Sentry, let's remove!
> Remove TODO.

- config/config.go
- config/mssql.go
- config/mssql_test.go
- config/postgres_test.go
- go.mod
- go.sum
- lib/debezium/converters/time.go
- lib/debezium/converters/time_duration.go
- lib/debezium/converters/time_duration_test.go
- lib/debezium/converters/time_test.go
- lib/postgres/scanner.go
This is going to be a series of PRs to support Microsoft SQL Server as a source. The full PR is here: https://github.com/artie-labs/reader/pull/386
The motivation of splitting this up is to make it easier to review.
* Upgrading Artie Transfer
* Adding MSSQL Config
* Adding additional converters
> Supporting MSSQL - Part 1

- sources/mssql/adapter/adapter.go
- sources/mysql/adapter/adapter.go
- sources/mysql/adapter/adapter_test.go
- sources/postgres/adapter/adapter.go
- sources/postgres/adapter/adapter_test.go
Removing unnecessary string manipulation for TopicSuffix
> MSSQL FF - TopicSuffix

- lib/mtr/mtr.go
See https://github.com/artie-labs/transfer/pull/696
> Replace `stringutil.Override` with `cmp.Or`

- writers/transfer/writer.go
> Snapshot strategy to support `destination.Baseline`

- lib/dynamo/message.go
- lib/dynamo/message_test.go
- lib/dynamo/parse_message.go
We haven't seen a Sentry related to these conversion errors, so let's hard fail
> [DynamoDB] Removing TODO

- integration_tests/mysql/main.go
- lib/mysql/schema/convert.go
- lib/mysql/schema/schema.go
- sources/mysql/adapter/adapter.go
* Adding support for `Geometry`
* Fix byte order bug with Point
> [MySQL] Support Geometry

- integration_tests/mysql/main.go
- lib/mysql/schema/convert.go
- lib/mysql/schema/schema.go
It's basically a freebie since Debezium treats this as a Geography object as well :)
> [MySQL] Support Linestring

- integration_tests/mysql/main.go
- lib/debezium/converters/decimal.go
- lib/debezium/converters/decimal_test.go
- lib/debezium/converters/money.go
- lib/debezium/converters/money_test.go
- lib/mssql/scanner_test.go
- lib/mssql/schema/schema.go
- lib/mssql/schema/schema_test.go
- lib/mysql/schema/schema_test.go
- lib/postgres/schema/schema.go
- lib/postgres/schema/schema_test.go
- lib/ptr/ptr.go
- sources/mssql/adapter/adapter.go
- sources/mysql/adapter/adapter_test.go
- writers/transfer/writer.go
Not really sure how this happened but I went through and resaved any file that had `^    ` in it.
> Convert spaces to tabs in go files

- lib/debezium/converters/int_test.go
- lib/postgres/scanner.go
Ran https://goreportcard.com/report/github.com/artie-labs/reader
> Fix a couple typos

- lib/mysql/schema/schema.go
Fixes https://github.com/artie-labs/reader/security/code-scanning/1
> Fix conversion

- go.mod
> Add Go patch version

- go.mod
- go.sum
- lib/kafkalib/writer.go
Reducing boilerplate by using Transfer's `kafkalib`
> Upgrading Artie Transfer + using Transfer's `kafkalib.NewConnection`

- sources/mongo/change_event.go
- sources/mongo/change_event_test.go
Adding test coverage to `NewChangeEvent` and `ToMessage`
> [MongoDB] Adding tests

- .github/workflows/gha-integration-tests.yaml
- Makefile
- integration_tests/mongo/docker-compose.yaml
- integration_tests/mongo/main.go
- integration_tests/postgres/main.go
- integration_tests/utils/utils.go
- sources/mongo/message.go
- sources/mongo/mongo.go
- sources/mongo/snapshot.go
- writers/transfer/writer_test.go
1. Adding MongoDB integration tests for snapshots
2. Enabling canonical mode when we're marshaling BSON into JSON extended, to maximize type preservation
> Adding MongoDB integration tests

- config/mongodb.go
- sources/mongo/snapshot.go
> [MongoDB] Support starting and ending primary keys

- lib/dynamo/primary_keys.go
- sources/dynamodb/dynamodb.go
- sources/dynamodb/snapshot/snapshot.go
- sources/dynamodb/snapshot/snapshot_iterator.go
- sources/dynamodb/stream/shard.go
- sources/dynamodb/stream/stream.go
No functionality changes, mainly moving stuff around in DynamoDB
> Moving DynamoDB files around

- go.mod
- go.sum
- lib/debezium/converters/decimal.go
- lib/debezium/converters/decimal_test.go
> Upgrade Deps + update references

- go.mod
- go.sum
- lib/debezium/converters/time_test.go
Upgrade Artie Transfer + fixing tests
> Upgrade Transfer.

- go.mod
- go.sum
- lib/debezium/converters/decimal_test.go
- lib/mssql/schema/schema_test.go
- lib/mysql/schema/schema.go
- lib/mysql/schema/schema_test.go
- lib/postgres/schema/schema_test.go
- lib/s3lib/s3lib_test.go
- sources/dynamodb/stream/shard.go
- sources/mysql/adapter/adapter_test.go
Upgrading Artie Transfer and updating usages of ptrs
> Upgrade Artie Transfer + updating ptrs

- lib/debezium/converters/money_test.go
- lib/mongo/message.go
- lib/ptr/ptr.go
- sources/mssql/adapter/adapter.go
Standardizing fully on Transfer
> Removing the ptrs pkg

- go.mod
- go.sum
- lib/debezium/converters/time.go
- lib/debezium/converters/time_test.go
> Upgrading deps

- go.mod
- go.sum
So we can pick up truncating exceeded values change from Transfer.
> Upgrade Deps

- .github/workflows/integration-tests.yaml
- Makefile
- integration_tests/mssql/docker-compose.yaml
- integration_tests/mssql/main.go
Adding the initial set of MSSQL integration tests
> Initial MSSQL integration tests

- go.mod
- go.sum
So it can pick up the Parquet change
> Upgrade Deps.

- config/mysql.go
- sources/mysql/streaming.go
- sources/mysql/streaming/types.go
- sources/mysql/streaming_test.go
1. Adding the ability to read offsets
2. Adding "included tables"
> [MySQL] Streaming support Part 2

- config/mysql.go
- sources/mysql/streaming/converter.go
- sources/mysql/streaming/converter_test.go
Main streaming working PR: https://github.com/artie-labs/reader/pull/552
This PR is pulling minor changes out of the main PR that we know for a fact we'll need.
> [MySQL] Minor changes

- lib/maputil/most_recent_map_test.go
- sources/mysql/streaming/converter.go
- sources/mysql/streaming/converter_test.go
Pulling out various conversion functions out into a separate PR to minimize the MySQL diff.
> Reducing MySQL streaming diff

- lib/kafkalib/writer.go
- sources/postgres/adapter/adapter.go
- sources/postgres/adapter/adapter_test.go
- sources/postgres/snapshot.go
- writers/transfer/writer.go
- writers/writer.go
- writers/writer_test.go
This PR adds the ability to use Transfer's logic to call create table for Postgres.
> Creating table despite no rows

- lib/debezium/transformer/light_transformer.go
- lib/debezium/transformer/transformer.go
The main PR lives here: https://github.com/artie-labs/reader/pull/552, we are now just splitting the diffs into separate PRs.
Standing up LightDebeziumTransformer that just transform rows and does not require an iterator
> Standing up the LightDebeziumTransformer

- sources/mysql/streaming/iterator.go
- sources/mysql/streaming/types.go
Main PR: https://github.com/artie-labs/reader/pull/552
This PR splits the diff out, so it's easier to review.
1. Handling initializing the Streaming Iterator
2. Handling Close + Committing offset
> [MySQL] Filling out more iterator logic

- sources/mysql/streaming/iterator.go
- sources/mysql/streaming/types.go
- sources/mysql/streaming/types_test.go
Setting up a scaffold for `Next`.
Once this PR is in, we'll have separate functions for
1. Parsing and persisting DDLs
2. Parsing events
> [MySQL] Filling out `Next`

- lib/antlr/alter_table_test.go
- lib/antlr/parse.go
- sources/mysql/streaming/ddl.go
- sources/mysql/streaming/ddl_test.go
- sources/mysql/streaming/iterator.go
- sources/mysql/streaming/types.go
1. Adding the ability to persist DDLs
2. Processing DDLs and coming up with the concept of Schema + Table adapters
> [MySQL] Persist DDLs

- config/mysql.go
- config/mysql_test.go
Adding validation for streaming
> [MySQL] Adding validation

- lib/mysql/converters/converters_test.go
Cleaning up + rewriting the tests
> Cleaning up tests

- lib/mysql/schema/schema.go
- lib/mysql/schema/schema_test.go
- sources/mysql/streaming/converter.go
- sources/mysql/streaming/converter_test.go
- sources/mysql/streaming/iterator.go
- sources/mysql/streaming/types.go
Putting changes out of https://github.com/artie-labs/reader/pull/571 and reducing the diff
> [MySQL] Reduce diff for DMLs

- sources/mysql/streaming/ddl.go
- sources/mysql/streaming/ddl_test.go
* Refactoring `SchemaAdapter.applyDDL`
* Adding support for column position
> [MySQL] Improve Table Adapters

- lib/debezium/converters/int.go
- lib/debezium/converters/int_test.go
- lib/debezium/converters/passthrough.go
- lib/mysql/schema/convert.go
- lib/mysql/schema/convert_test.go
- lib/mysql/schema/schema.go
- lib/mysql/schema/schema_test.go
- sources/mysql/streaming/converter.go
- sources/mysql/streaming/ddl.go
- sources/mysql/streaming/dml.go
- sources/mysql/streaming/iterator.go
This PR widens our converters to handle the different data types that are coming from the MySQL streaming library.
> [MySQL] Widen converters

- lib/antlr/alter_table.go
- lib/antlr/create_table.go
- lib/antlr/create_table_test.go
- lib/antlr/parse.go
- lib/mysql/schema/schema.go
- lib/mysql/schema/schema_test.go
- sources/mysql/streaming/ddl/ddl.go
- sources/mysql/streaming/dml.go
- sources/mysql/streaming/iterator.go
* Skipping additional types
* Improving error messages
* Better checks around schema and offsets
> [MySQL] Addressing additional edge cases

- README.md
- lib/debezium/transformer/light_transformer.go
- sources/mysql/streaming/converter.go
- sources/mysql/streaming/dml.go
- sources/mysql/streaming/iterator.go
Filling out more of the source details so it has a closer resemblance to Debezium + marking MySQL as supported.
> [MySQL] Implementing the source payload

- sources/mysql/streaming/dml.go
- sources/mysql/streaming/iterator.go
We were not filtering correctly for the different schemas on the MySQL server. Which caused a discrepancy in columns and values we got back.
> [MySQL] Filter schemas

- lib/debezium/transformer/light_transformer.go
- lib/debezium/transformer/transformer.go
- lib/debezium/transformer/transformer_test.go
- lib/dynamo/message.go
- lib/kafkalib/writer.go
- lib/kafkalib/writer_test.go
- lib/mongo/message.go
- lib/types.go
- sources/mysql/streaming/dml.go
- writers/writer_test.go
Further alignment around Reader and Debezium by passing the schema (if available) into the Kafka partition key.
> [MySQL FF] Passing schema into the Kafka partition key 

- config/mysql.go
- sources/mysql/mysql.go
- sources/mysql/settings.go
- sources/mysql/streaming.go
- sources/mysql/streaming/iterator.go
- sources/mysql/streaming/offset.go
- sources/mysql/streaming/types.go
- sources/mysql/validate.go
> [MySQL] Supporting GTID

- lib/antlr/alter_table_test.go
- lib/antlr/create_table_test.go
- lib/antlr/types.go
- lib/antlr/util.go
Default value is optionally set, let's make this a pointer so we can tell the difference between not set and set to empty string.
> [MySQL] Default value to be a pointer

- lib/antlr/create_table.go
- lib/antlr/create_table_test.go
- lib/antlr/parse.go
- lib/antlr/types.go
Adding support to our DDL library to understand `CREATE TABLE LIKE`
> [DDL] Support `CREATE TABLE LIKE`

- lib/antlr/parse.go
- lib/mysql/schema/schema.go
- lib/mysql/schema/schema_test.go
- sources/mysql/streaming/ddl/ddl.go
1. Skipping additional events that we don't care about
2. Handling different permutations of charset
3. Handling drop table
> More MySQL Improvements

- integration_tests/mongo/main.go
- integration_tests/mssql/main.go
- integration_tests/mysql/main.go
- integration_tests/postgres/main.go
- integration_tests/utils/utils.go
- lib/debezium/transformer/transformer.go
- lib/dynamo/message.go
- lib/kafkalib/message.go
- lib/kafkalib/writer.go
- lib/kafkalib/writer_test.go
- lib/mongo/message.go
- sources/dynamodb/snapshot/snapshot_iterator.go
- sources/dynamodb/stream/shard.go
- sources/mongo/snapshot.go
- sources/mongo/streaming.go
- sources/mysql/streaming/dml.go
- sources/mysql/streaming/iterator.go
- writers/transfer/writer.go
- writers/writer.go
- writers/writer_test.go
Moving it under `kafkalib` and renaming it from `RawMessage` -> `Message`
> [Kafka] Rename + Moving `RawMessage`
