artie-labs/reader

- lib/ttlmap/ttlmap.go
- lib/ttlmap/ttlmap_suite_test.go
- lib/ttlmap/ttlmap_test.go
- sources/dynamodb/dynamodb.go
- sources/dynamodb/offsets/offsets.go
- sources/dynamodb/offsets/offsets_test.go
In this PR, we are making the following changes.
1. Introduction to `ttlmap`, we are implementing our own k/v store that will periodically flush to disk and purge. 
2. We are saving the shardId that we have fully processed so we don't waste time iterating over it
3. We are using `gob` to load and unload offset file to disk. `gob` allows us to save the existing type encoding.
We implemented our own `k/v` store that is durable + TTL based because we want the pod to have 0 overhead and have to be dependent on Redis.
> [Optimization] Offset storage + saving processed shards

- sources/dynamodb/dynamodb.go
As per title. We were not using it.
> Actually using the AWS service account provided

- sources/dynamodb/dynamodb.go
- sources/dynamodb/shard.go
We were previously only processing one shard at a time and doing things in serial. We were also repeatedly hammering at the `GetRecords(...)` API when there were records from the last fetch.
1. Adding go routines to do parallel processing at the shard level
2. Adding a sleep so that we do not hammer the `GetRecords` API
> [DynamoDB] Processing multiple shards at once

- lib/ttlmap/ttlmap.go
- lib/ttlmap/ttlmap_test.go
- sources/dynamodb/dynamodb.go
- sources/dynamodb/offsets/offsets.go
- sources/dynamodb/shard.go
After the latest PR, #12 - we are now processing multiple shards concurrently. However, we did not have shards auto-discovery built in.
> [Optimization] New go-routine to ensure new shards are being discovered

- lib/ttlmap/ttlmap.go
We are doing this to protect against 2 things.
* Bad data, if there are no data in the offset file, we are loading a nil map to `ttlMap.data` which can cause a panic
* Potential concurrent r/w panic with Flush + GC
> Guardrail around panic and bad data

- sources/dynamodb/dynamodb.go
When a DynamoDB stream has more than 100 shards, the API for `DescribeStream` requires one to paginate. 
We were previously not doing so, this PR makes it such that we will iterate over all the shards based on `LastEvaluatedShardId` from `DescribeStream`
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_DescribeStream.html
> ScanForNewShards should iterate

- config/config.go
- config/dynamodb.go
- examples/dynamodb/service_account.tf
- lib/dynamo/message.go
- lib/dynamo/parse_message.go
- lib/dynamo/parse_message_test.go
- lib/s3lib/s3lib.go
- lib/s3lib/s3lib_test.go
- sources/dynamodb/dynamodb.go
- sources/dynamodb/primary_keys.go
- sources/dynamodb/snapshot.go
In this PR, we are adding the ability to take a snapshot of a DynamoDB table. 
Snapshot works in 2 ways:
1. You can pass in the S3 folder, or
2. You can specify the files to read which will have parallelism.
```yaml
dynamodb:
snapshot: true
snapshotSettings:
folder: s3://artie-transfer-test/AWSDynamoDB/EXPORT_ID/data
specifiedFiles:
- bucket: artie-transfer-test
key: AWSDynamoDB/EXPORT_ID/data/file.json.gz
```
If you pass in both, the folder will be ignored and Artie Reader will prioritize specifiedFiles.
> DynamoDB Snapshot

- constants/constants.go
- go.mod
- go.sum
- lib/kafkalib/batch.go
- lib/mtr/datadog.go
- lib/mtr/mtr.go
- lib/ttlmap/ttlmap_suite_test.go
- main.go
It was previously using Transfer's Datadog client, which caused a panic since the context keys are no longer the "same" since they're no longer string-based.
We are exclusively using our own Datadog client now.
> Refactor to use its own Datadog client

- .github/workflows/gha-go-test.yaml
https://github.com/actions/setup-go?tab=readme-ov-file#v4 has caching by default.
> Add Go package caching to GitHub Action

- config/config.go
- lib/kafkalib/batch.go
- lib/kafkalib/kafka.go
- lib/mtr/mtr.go
- lib/ttlmap/ttlmap.go
- main.go
- sources/dynamodb/dynamodb.go
- sources/dynamodb/shard.go
- sources/dynamodb/snapshot.go
- Uppercase log messages
- Add arguments in log call instead of using `.With()`
> Standardize logging

- constants/constants.go
Let's reduce Kafka publish size to 2.5k to be backwards compatible
> [Kafka Publish Size] Reduce to 2.5k

- lib/kafkalib/batch.go
If sending a batch fails we are sending the next batch on the next attempt rather than the batch that failed.
> Fix bug fetching new batches on subsequent attempts

- lib/kafkalib/writer.go
- lib/postgres/iterator.go
- lib/types.go
That way `lib/kafkalib` and `lib/postgres` do not need to know about each other.
> Move RawMessage out of kafkalib

- lib/postgres/iterator.go
- Rename `limit` to `batchSize`
- Exit early when we get back an empty array of rows
- Guard against calling `Next()` on an iterator that's already completed
- Return a closed iterator when scanning a table without any rows
> Cleanup postgres table iterator

- lib/postgres/iterator.go
- lib/postgres/scan.go
The iterator shouldn't need to be concerned with `firstRow`, `lastRow`, or `done`, those should be the responsibility of the scanner. It's likely we can clean up the actual scanning code a bit after this, but I'm going to clean things up in stages.
This separates scanning the table from encoding the table as Debezium payloads.
> Move postgres scanning logic out of table iterator

- lib/postgres/iterator.go
- lib/postgres/scan.go
Round 2
TODO after this round:
- Rename `startScanning` -> `scan`
- Rename `attempts` -> `attemptsLeft`
- Rename `firstRow` -> `isFirstRow`
- Rename `lastRow` -> `isLastRow`
- Move scanner struct to top of `scan.go`
- Copy primary keys when instantiating scanner so we aren't mutating the table's primary keys
> Clean up postgres scanner

- lib/postgres/primary_key/primary_keys.go
- lib/postgres/primary_key/primary_keys_test.go
- lib/postgres/scan.go
Scanning a table mutates the primary keys so we shouldn't be directly passing in the table's primary keys.
> Use a copy of the primary keys when scanning a table

- lib/iterator/iterator.go
- lib/iterator/iterator_test.go
- lib/kafkalib/writer.go
- main.go
- sources/postgres/snapshot.go
- Pass context as a parameter
- Add a generic batch iterator and use it instead of `NewBatch`
> Clean up Kafka batch writer

- lib/postgres/queries/queries.go
- lib/postgres/queries/queries_test.go
Our previous approach for retrieving the last entry in a table involved a simple SQL query that selected the primary key and ordered the results in descending order. This method was straightforward for tables with a single primary key but proved inadequate for tables with composite primary keys.
| Aspect | Before | After |
| --------------- | ------ | ------ |
| Single PK | `SELECT pk FROM table ORDER BY pk DESC LIMIT 1;` | No change required. |
| Composite PK | `sql SELECT pk_1, pk_2 FROM table ORDER BY pk_1, pk_2 DESC LIMIT 1;` | `sql SELECT pk_1, pk_2 FROM table ORDER BY pk_1 DESC, pk_2 DESC LIMIT 1;` |
> Postgres - Composite key value fix

- lib/debezium/numeric_test.go
- lib/postgres/parse.go
- lib/postgres/parse/parse.go
- lib/postgres/parse/parse_test.go
- lib/postgres/parse_test.go
- lib/postgres/scan.go
After the `pq => pgx` upgrade, the raw value from the SQL driver has changed for most data types from `[]byte` to `string`.
This PR fixes all of these data types:
* Geometry
* Point
* Bit
* Numeric and Variable Numeric
* UUID
* Enums
Data coming in for `JSON` is still type `[]byte`
> [Postgres] Fix native parsing

- lib/jitter.go
`2 ** x` is equivalent to `1 << x`, but doesn't require casting to `float64`. Proof https://go.dev/play/p/u2oW25Xes3Z
> Optimize jitter function

- config/config.go
- config/postgres.go
- config/postgres_test.go
- examples/postgres.yaml
- lib/postgres/columns.go
- lib/postgres/context.go
- `port` is now defined as a `uint16` which aligns perfectly with the TCP/UDP port range of 0 to 65,535
- `userName` renamed to `username` (`userName` is still currently supported as a fallback)
- For table config `limit` renamed to `batchSize` (`limit` is still currently supported as a fallback)
> Postgres config improvements

- lib/postgres/context.go
- main.go
- sources/postgres/snapshot.go
This makes the PostgreSQL conform to *almost* the same interface as the DynamoDB source.
> Separate PostgreSQL init from run

- lib/postgres/columns.go
- lib/postgres/columns_test.go
- lib/postgres/debezium/data_type.go
- lib/postgres/debezium/fields.go
- lib/postgres/debezium/fields_test.go
- lib/postgres/debezium/values.go
- lib/postgres/debezium/values_test.go
- lib/postgres/parse.go
- lib/postgres/parse_test.go
- lib/postgres/queries/queries.go
- lib/postgres/queries/queries_test.go
- lib/postgres/schema/schema.go
- lib/postgres/schema/schema_test.go
This creates a new package `lib/postgres/schema` that contains the postgres data types and queries for describing postgres tables. The idea is that the `schema` package should not know about anything `debezium` related and also be stateless.
This PR just moves things around, there are no code changes.
> Consolidate postgres schema code

- lib/postgres/columns.go
- lib/postgres/parse_test.go
- lib/postgres/schema/schema.go
- lib/postgres/schema/schema_test.go
Splits out the stateless part of describing a postgres table + determining the column types from adding fields to our stateful `Table` struct.
> Add a stateless postgres describe table function

- lib/kafkalib/writer.go
- lib/mtr/datadog.go
- lib/mtr/mtr.go
- lib/postgres/message.go
- lib/postgres/message_test.go
- main.go
- sources/dynamodb/dynamodb.go
- sources/mongo/mongo.go
- sources/postgres/snapshot.go
- sources/source.go
1. Using `Null Metrics Provider` from `Transfer` if metrics was not passed in.
2. Cleaning up code to not rely on a pointer to an interface
> Using Null metrics provider if none is available

- lib/postgres/columns.go
- lib/postgres/schema/schema.go
- sources/postgres/snapshot.go
I don't think we need to query for columns again since we already have them from when we described the table.
> [postgres] Kill extra query for table columns

- lib/postgres/message_test.go
- lib/postgres/scan.go
- lib/postgres/table.go
Rename `OriginalColumns` to `Columns` and store the full `Column` struct instead of just the name. Also kill `ColumnsCastedForScanning` and determine on the fly when needed.
> [postgres] Store `Column` structs on table

- lib/postgres/parse.go
- lib/postgres/parse_test.go
- lib/postgres/scan.go
- lib/postgres/table.go
The only think we needed `ColName` for was to look up the `DataType` using `fields`, instead we can just pass the `DataType` to `ParseValue` directly.
> [postgres] Pull fields out of `ParseValue`

- lib/postgres/primary_key/primary_keys.go
- lib/postgres/scan.go
- lib/postgres/scan_test.go
`KeysToValueList ` is postgres specific where as the rest of the primary key code is database agnostic and can be shared with mysql. Will move it to `lib/rdbms` after this.
> [postgres] Move `KeysToValueList` calls to `scanTableQuery`

- lib/postgres/scan.go
- lib/postgres/scan_test.go
Extract the logic for deciding when to quote a value to a new function `shouldQuoteValue` and then test all the postgres types.
> [postgres] Test logic for quoting values in scan query

- lib/postgres/scan_test.go
When running the test we were getting:
```
WARN Skipping field from optional schema b/c we cannot determine the data type field=Money
WARN Skipping field from optional schema b/c we cannot determine the data type field=Numeric
```
because the columns did not have scale and precision set.
> [postgres] Fix `TestShouldQuoteValue` test cases

- lib/postgres/scan.go
- lib/postgres/scan_test.go
Based on https://github.com/artie-labs/reader/pull/145 I determined that the `val` passed to `shouldQuoteValue` is extraneous. Instead of the complexity of:
- converting a `Column` to a `Field`
- converting the `Field` to a `KindDetails`
- For the decimals the existing behavior https://github.com/artie-labs/transfer/blob/cdf82a6e5b2ff966aeb1e1468fd149dc27417c21/lib/debezium/schema.go#L92 checks that we can parse the scale and if not returns in invalid type, however since we quoted invalid types and also quote decimal types this doesn't actually matter.
- switching on `KindDetails`
we can just do a simple switch on the `Column`'s `DataType`. I already have tests for all of the Postgres `DataType`s so we can be sure that this change preserves the existing behavior.
> [postgres] Modify `shouldQuoteValue` to check types directly

- sources/postgres/transformer/fields.go
- sources/postgres/transformer/fields_test.go
- sources/postgres/transformer/transformer.go
- sources/postgres/transformer/values_test.go
This kills the `lib/postgres/debezium` package.
> [postgres] Move `fields.go` to `sources/postgres/transformer`

- lib/postgres/errors.go
- lib/postgres/errors_test.go
Because we're wrapping errors the final error is never exactly `"sql: no rows in result set"`, so when a table is empty we aren't detecting it properly:
```
Feb 17 19:12:43.681 ERR Failed to run postgresql snapshot err="failed to load configuration for table user_games: failed to retrieve bounds for primary keys: failed to retrieve lower bounds for primary keys: sql: no rows in result set"
exit status 1
```
Using `errors.Is` checks the underlying error and fixes this bug.
> [postgres] Fix bug with handling empty tables

- sources/postgres/snapshot.go
- sources/postgres/transformer/transformer.go
- sources/postgres/transformer/transformer_test.go
This will allow the `DebeziumTransformer ` to be source agnostic so that it can be reused for `MySQL`. For this PR I tried to make as few changes as possible so that it would be easier to review. In the next PR I will move `DebeziumTransformer` to `lib/transformer`.
> [postgres] Add adapter for `DebeziumTransformer`

- lib/postgres/scan.go
- lib/rdbms/primary_key/primary_key.go
For MySQL we will just use the values returned from the database rather than coercing them to strings like we do for PostgreSQL.
> Allow primary key values to be any type

- lib/postgres/scan.go
When there aren't any rows left we were updating primary keys to have the value of `""` because `lastRow` was a `nil` array. This wasn't breaking anything, but there's no need to mutate primary keys if we're done scanning.
> [postgres] Return early during scan when no rows

- lib/postgres/scan.go
- lib/postgres/scan_test.go
Currently we use an inclusive upper bound for the scan except in the situation where the previous scan returned a non-zero amount of rows yet fewer rows than the batch size. In this case we do one final scan but this time we do not use an inclusive upper bound, which theoretically means that we're not getting back the very last row. In practice this isn't actually an issue because the scan which returned an amount of rows smaller than the batch size will have returned the last row, so we'll always get it back.
This code was originally introduced here: https://github.com/artie-labs/custom-snapshots/pull/1/files#diff-63a7de3e0e433472f281806bac7775b97ff1a41449e5cefa4b125ed196a4fc2aR133
> [postgres] Always use inclusive upper bound for scans

- lib/mysql/scanner/scanner.go
- lib/mysql/schema/schema.go
- lib/postgres/scan.go
- lib/postgres/scan_test.go
- lib/postgres/schema/schema.go
- lib/rdbms/primary_key/primary_key.go
- lib/rdbms/primary_key/primary_keys.go
- lib/rdbms/primary_key/primary_keys_test.go
Now that we're initializing the `Keys` struct with all the keys we don't have to ever add new keys, and we never modify the ending value so no need to pass it in.
> [rdbms] Change primary_key `Upsert` to `UpdateStartingValue`

- lib/postgres/parse.go
- lib/postgres/scan.go
- lib/postgres/scan_test.go
- lib/postgres/table.go
We're already doing a `fmt.Sprint()` for primary key values here: https://github.com/artie-labs/reader/pull/197/files#diff-eb76bea08e483c31dcfdd81272705c460694b4cc6fb60a396854c96d676dd9adR155 when we build the scan query, so we don't need to do so when building and updating primary keys.
> [postgres] Remove redundant pk `fmt.Sprint()` calls

- lib/postgres/parse.go
- lib/postgres/parse_test.go
- lib/postgres/scan.go
- lib/postgres/scan_test.go
- lib/postgres/table.go
- lib/timeutil/parse.go
Instead of converting primary key time.Time` values to strings when we store them in the `primary_key.Keys` we can just convert them to strings when we need to use them to build the scanning query.
> [postgres] Convert `time.Time` values to string at query time

- lib/postgres/cast.go
- lib/postgres/cast_test.go
- lib/postgres/scan.go
- lib/postgres/scan_test.go
- lib/postgres/schema/schema.go
- lib/postgres/schema/schema_test.go
- sources/postgres/adapter/fields.go
- sources/postgres/adapter/fields_test.go
- sources/postgres/integration_test/main.go
We test all of these types in our integration test and with the exception of `inet` removing the `::text` casting produces the same output.
Removing the `::text` casting from `inet` changes the value from `192.168.1.5/32` to `192.168.1.5`.
> [postgres] Kill `TextThatRequiresEscaping`

- lib/postgres/cast.go
- lib/postgres/cast_test.go
- lib/postgres/scanner.go
- lib/postgres/schema/schema.go
- lib/postgres/schema/schema_test.go
This will ensure that we update `castColumn` when we add a new `DataType`.
I checked that `castColumn` currently works for all of the types defined here: https://github.com/artie-labs/reader/blob/60f0d745c6b8f90a49b7c374440d1be0ee5a3836/lib/postgres/schema/schema.go#L16
> [postgres] Change `castColumn` to error for unhandled types

- lib/mysql/schema/schema.go
- lib/mysql/schema/schema_test.go
- sources/mysql/adapter/adapter_test.go
Since we error when we can't determine the data type we should never expect to see a `InvalidDataType` anywhere in code.
> [mysql] Kill `InvalidDataType`

- lib/postgres/scanner.go
- lib/postgres/scanner_test.go
We should be able to depend on the Go type of `value` when we encode it for use in a query. In order to safely move towards that behavior we'll first log when we encounter a value that has a different type than the type we expect for a column and in those cases fall back to the legacy behavior. Once we've run this code for a while without error logs we'll switch to returning an error instead.
Note that `convertToStringForQuery` is only used to encode primary key values for use in the scanner query.
The longterm goal is to switch to doing a parameterized query and letting the driver take care of this string conversion.
> [postgres] Use value type in `convertToStringForQuery`

- lib/logger/logger.go
- main.go
Right now, when we call `logger.Fatal(...)`, it just exits the program. However, the error doesn't actually make it to Sentry since the program has been exited.
This PR refactors the logger such that it will call a list of clean up functions like `sentry.Flush(...)`, this is following the same pattern as Logrus
> Update Logging handler

- lib/postgres/cast.go
- lib/postgres/cast_test.go
- lib/postgres/scanner.go
- lib/postgres/scanner_test.go
- lib/postgres/schema/schema.go
- lib/postgres/schema/schema_test.go
- sources/mysql/adapter/adapter.go
- sources/postgres/adapter/adapter.go
- sources/postgres/adapter/adapter_test.go
- sources/postgres/adapter/fields.go
- sources/postgres/adapter/fields_test.go
- sources/postgres/adapter/values_test.go
Kill `InvalidDataType` and instead throw an error in `DescribeTable` if we encounter a column type we don't support.
> [postgres] Stricter column type handling

- .github/workflows/gha-go-test.yaml
- goreleaser.dockerfile
> [gha] Use prebuilt binary for `staticcheck`

- integration_tests/postgres/main.go
We have special logic for Postgres numeric columns that have variable precision, so adding it explicitly to the integration test. This help avoid bugs in https://github.com/artie-labs/reader/pull/246
> [postgres] Test variable numeric data type

- sources/postgres/adapter/adapter.go
- sources/postgres/adapter/converters.go
- sources/postgres/adapter/fields.go
- sources/postgres/adapter/values.go
The `converters.TimestampConverter` returns an error if the value is not a `time.Time`, so adding a new converter just for postgres that preserves the existing functionality that logs if the value is not `time.Time` with the goal of eventually switching to `converters.TimestampConverter`.
> [postgres] Add `PgTimestampConverter`

- lib/mysql/schema/convert.go
- lib/mysql/schema/convert_test.go
We were previously failing on this, however this is valid in MySQL.
> The "0000-00-00" date is often used in MySQL databases as a placeholder for an unknown or default date. However, this value is not considered a valid date in many contexts, including some programming languages or database drivers that might be used to interact with MySQL.
> Skip MySQL Zero Dates

- lib/debezium/converters/time.go
- lib/debezium/converters/time_test.go
`time.Duration` [doesn't work for durations > 290 years](https://pkg.go.dev/time#pkg-types).
> A Duration represents the elapsed time between two instants as an int64 nanosecond count. The representation limits the largest representable duration to approximately 290 years.
> [debezium] Fix `DateConverter` for dates > 290 years from 1970

- integration_tests/postgres/main.go
- lib/debezium/converters/time.go
- lib/debezium/converters/time_test.go
- lib/postgres/cast.go
- lib/postgres/cast_test.go
- lib/postgres/parse/parse.go
- lib/postgres/parse/parse_test.go
- lib/postgres/scanner.go
- lib/postgres/scanner_test.go
- lib/postgres/schema/schema.go
- lib/postgres/schema/schema_test.go
- sources/postgres/adapter/adapter.go
- sources/postgres/adapter/adapter_test.go
- sources/postgres/adapter/converters.go
- sources/postgres/adapter/converters_test.go
- No longer need to cast `time without time zone` columns
- Still have to cast `time with time zone` but now it's just converting to `UTC` rather than Unix epoch
- We now support using `time without time zone` as a primary key 
- `time without time zone` is harder to support as `pgtype.Time` doesn't parse them properly: https://github.com/jackc/pgx/issues/1940
> [postgres] Add `PgTimeConverter`

- lib/mysql/schema/schema.go
- lib/postgres/scanner_test.go
- lib/postgres/schema/schema.go
This way if we forget to pass a `DataType` in to a struct it'll default to the `0` value which is invalid and we'll get an error in our switch statements rather than `Bit` or `TinyInt`.
> [mysql,postgres] Offset `DataType`s by one

- lib/postgres/scanner.go
- lib/postgres/scanner_test.go
Instead of quoting a column based on its `DataType` we'll just quote it if it's a string and otherwise not quote it.
> [postgres] Kill `shouldQuoteValue`

- lib/postgres/cast.go
- lib/postgres/cast_test.go
Since casting is the exception we don't need to be explicit about which columns are not cast.
> [postgres] Default to not casting columns

- integration_tests/mysql/main.go
- integration_tests/postgres/main.go
- lib/debezium/converters/decimal.go
- lib/debezium/converters/decimal_test.go
- sources/mysql/adapter/adapter_test.go
- sources/postgres/adapter/adapter_test.go
- sources/postgres/adapter/converters.go
- sources/postgres/adapter/converters_test.go
The type for `org.apache.kafka.connect.data.Decimal` fields should be `bytes`: https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-decimal-types
> [debezium] `bytes` type for `org.apache.kafka.connect.data.Decimal`

- integration_tests/postgres/main.go
- lib/debezium/converters/decimal.go
- lib/debezium/converters/decimal_test.go
- lib/debezium/numeric.go
- lib/debezium/numeric_test.go
- sources/postgres/adapter/adapter_test.go
- sources/postgres/adapter/converters.go
- sources/postgres/adapter/converters_test.go
When a `[]byte` is marshalled to JSON [it'll be base64 encoded](https://github.com/golang/go/blob/0a6f05e30f58023bf45f747a79c20751db2bcfe7/src/encoding/json/encode.go#L781), so our value converters can just return byte arrays.
> [debezium] Return `[]byte` from decimal converters

- lib/debezium/converters/time.go
- lib/debezium/converters/time_test.go
Rather than relying on `Time.MarshalJSON` to convert `time.Time` to a string do the conversion in `TimestampConverter` so we know exactly what format is being used. `Time.MarshalJSON` [uses RFC 3339 format with sub-second precision](https://github.com/golang/go/blob/0a6f05e30f58023bf45f747a79c20751db2bcfe7/src/time/time.go#L1365)
This also seems more correct since we're defining the field type as string https://github.com/artie-labs/reader/pull/301/files#diff-5de60c74c1cf57a3f6e6d17dc239b2e77d2e9b9ac954257b55972fdc22926f0cR76
> [debezium] Format `time.Time` to string in `TimestampConverter`

- lib/postgres/cast_test.go
These tests all test the same thing as the `schema.Text` case since they use the default behavior.
> [postgres] Remove extraneous `castColumn` test cases

- lib/postgres/schema/schema.go
- lib/postgres/schema/schema_test.go
- lib/postgres/table.go
Since the only [two columns type that require casting ](https://github.com/artie-labs/reader/blob/970631c7c8f25b34ad687eec142308e2e739efb7/lib/postgres/scanner.go#L140)(`schema.Array`, `schema.TimeWithTimeZone`) are [not supported as primary key types](https://github.com/artie-labs/reader/blob/970631c7c8f25b34ad687eec142308e2e739efb7/lib/postgres/scanner.go#L19) we can remove the logic that casts columns when we fetch the primary key values.
> [postgres] Remove casting from primary key values query

- lib/kafkalib/errors.go
- lib/kafkalib/errors_test.go
- lib/kafkalib/kafka.go
- lib/kafkalib/message.go
- lib/kafkalib/message_test.go
- lib/kafkalib/writer.go
- sources/mysql/adapter/adapter.go
- sources/postgres/adapter/adapter.go
- sources/postgres/adapter/adapter_test.go
- sources/postgres/adapter/transformer_test.go
Main changes here are:
1. Making public functions that don't need to be public, private.
2. Removing the pointer from converting raw message into Kafka message
3. Making the Adapter for PostgreSQL and MySQL public as they are being returned
> Minor Reader Improvements

- lib/kafkalib/writer.go
Moves checking `cfg.GetPublishSize()` from `WriteRawMessages` to `NewBatchWriter` so that we fail fast.
> [kafka] Validate publish size when creating `BatchWriter`

- go.mod
- go.sum
Version `0.27.0` has a [change for unwrapping errors](https://github.com/getsentry/sentry-go/pull/792) so hopefully this improves error grouping in Sentry.
> Upgrade sentry to `v0.27.0` and transfer to `v1.22.26`

- integration_tests/mysql/main.go
- integration_tests/postgres/main.go
- integration_tests/utils/utils.go
- lib/debezium/transformer/transformer.go
- lib/debezium/transformer/transformer_test.go
- lib/dynamo/message.go
- lib/kafkalib/message.go
- lib/kafkalib/message_test.go
- lib/types.go
- lib/writer/writer_test.go
- sources/mongo/message.go
- sources/mongo/message_test.go
- sources/postgres/adapter/transformer_test.go
This will return the payload in the Artie Event format which will make it easier for us to do subsequent saves.
> Return `cdc.Event` instead of `any`

- lib/debezium/converters/decimal.go
- lib/debezium/converters/decimal_test.go
- sources/postgres/adapter/adapter_test.go
By returning a map instead of a struct we can test the output of `VariableNumericConverter.Convert` using `Field.DecodeDebeziumVariableDecimal`.
> [debeziuim] Kill `VariableScaleDecimal`

- config/config.go
- config/config_test.go
- lib/debezium/converters/bit.go
- lib/debezium/transformer/transformer.go
- lib/mysql/scanner/scanner.go
- lib/postgres/scanner.go
- lib/postgres/scanner_test.go
- lib/rdbms/column/column.go
- main.go
Just learned about [%q](https://pkg.go.dev/fmt#:~:text=%25q%09a%20double%2Dquoted%20string%20safely%20escaped%20with%20Go%20syntax) which prints strings inside of double quotes.
> Use `%q` instead of `"%s"`

- lib/mssql/scanner.go
- lib/mssql/schema/schema.go
- lib/mssql/table.go
- lib/mysql/scanner/scanner.go
- lib/mysql/schema/schema.go
- lib/mysql/table.go
- lib/postgres/scanner.go
- lib/postgres/schema/schema.go
- lib/postgres/table.go
I started naming the schema functions prefixed with `Get` back before I knew that `Get` [wasn't idiomatic Go](https://go.dev/doc/effective_go#:~:text=it%27s%20neither%20idiomatic%20nor%20necessary%20to%20put%20Get%20into%20the%20getter%27s%20name), plus this makes it more obvious that a database call is going to be performed.
> Rename database functions to start with `Fetch` instead of `Get`

- lib/kafkalib/errors.go
- lib/kafkalib/errors_test.go
- lib/kafkalib/writer.go
Using `errors.Is` is not capturing the MessageTooLarge error.
This is because the Kafka writer calls: https://github.com/segmentio/kafka-go/blob/ebca72eaee918d303c532feb7ff29afdcd8c2efa/writer.go#L634 which is: https://github.com/segmentio/kafka-go/blob/ebca72eaee918d303c532feb7ff29afdcd8c2efa/error.go#L644-L652
This returns the struct https://github.com/segmentio/kafka-go/blob/ebca72eaee918d303c532feb7ff29afdcd8c2efa/error.go#L644-L652
The tests in the SDK is also using `errors.As`: https://github.com/segmentio/kafka-go/blob/ebca72eaee918d303c532feb7ff29afdcd8c2efa/writer_test.go#L383-L385
> [Kafka] Update error assertion for MessageTooLargeError

- lib/mssql/scanner.go
- lib/mssql/scanner_test.go
- lib/mysql/scanner/scanner.go
- lib/mysql/scanner/scanner_test.go
- lib/postgres/scanner.go
- lib/postgres/scanner_test.go
- lib/rdbms/scan/scan.go
- lib/rdbms/scan/scan_test.go
MSSQL now supports all data types as primary keys.
I also modified the signature of `BuildQuery` to return an error as the MySQL SDK requires us to explicitly parse out `time.Time`
> [MSSQL] To support date, time, datetime primary keys

- lib/dynamo/message.go
Adding Sentry so we can gauge whether this happens or not.
If it doesn't, then we should address the TODO and return an error.
> [DynamoDB] Adding Sentry

- sources/dynamodb/offsets/offsets.go
The current buffer is too short as it only gives 2 hours for garbage collection to run
> [DynamoDB] Increase shard buffer from 26h => 48h.

- sources/dynamodb/offsets/offsets.go
- sources/dynamodb/shard.go
- sources/dynamodb/stream.go
There is an edge case with DynamoDB where if the same record appeared in two different DynamoDB shards (parent -> child), we are processing them in parallel as opposed to sequentially.
This is mainly an issue if a DynamoDB stream hasn't been consumed in a while since shards are records and time based.
Per [SDK docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html#Streams.Processing):
> Because shards have a lineage (parent and children), **an application must always process a parent shard before it processes a child shard**. This helps ensure that the stream records are also processed in the correct order. (If you use the DynamoDB Streams Kinesis Adapter, this is handled for you. Your application processes the shards and stream records in the correct order. …
> DynamoDB - Respect lineage

- lib/persistedmap/persistedmap.go
- lib/persistedmap/persistedmap_test.go
- lib/ttlmap/ttlmap.go
Adding a new storage option called PersistedMap which is necessary for storing offsets for different databases when we implement streaming
> Adding PersistedMap

- .goreleaser.yaml
Fixes:
> only configurations files on  version: 2  are supported, yours is  version: 0 , please update your configuration
See https://goreleaser.com/blog/goreleaser-v2/
> Add version to GoReleaser config

- lib/mysql/schema/convert.go
- lib/mysql/schema/convert_test.go
If strict mode isn't enabled, MySQL may allow invalid datetime / timestamps.
> MySQL datetime guardrail

- sources/mongo/message.go
- sources/mongo/message_test.go
- sources/mongo/mongo.go
- sources/mongo/snapshot.go
- writers/transfer/writer_test.go
This PR is to break the main PR: https://github.com/artie-labs/reader/pull/429 into reviewable diffs with the ultimate goal of supporting MongoDB streaming
> Supporting MongoDB streaming part 1

- config/config.go
- lib/kafkalib/writer.go
- main.go
By doing this, we will now be able to produce Kafka messages to a Kafka cluster w/ SHA 512 enabled. 
This is required when we're rolling our own Kafka clusters
> [Kafka] Supporting SCRAM-SHA-512

- integration_tests/postgres/main.go
- lib/postgres/parse/parse.go
- lib/postgres/parse/parse_test.go
- lib/postgres/scanner.go
- lib/postgres/scanner_test.go
- lib/timeutil/exact.go
- lib/timeutil/exact_test.go
- sources/postgres/adapter/adapter.go
- sources/postgres/adapter/adapter_test.go
- sources/postgres/adapter/converters.go
As per title. This is following the same spec as Debezium.
> [Postgres] Native support for `TIME WITH TIME ZONE`

- lib/ttlmap/ttlmap.go
- sources/dynamodb/dynamodb.go
- sources/dynamodb/offsets/offsets.go
- sources/dynamodb/shard.go
We were previously getting deadlocks from time to time - which would lead us to get paged. 
Upon closer inspection - this is happening because we are not retrying the shard correctly. This PR fixes that.
> [DynamoDB] Handling DynamoDB network error.

- lib/dynamo/message.go
- lib/dynamo/message_test.go
- lib/dynamo/parse_message.go
We are not passing the after schema object from DynamoDB right now. A side effect of not passing this is that we are not creating primary keys in Dynamo.
This PR adds support of this.
> [DynamoDB] Pass after schema objects

- lib/dynamo/message.go
- lib/dynamo/message_test.go
- scripts/dynamo/load.go
While reviewing https://github.com/artie-labs/reader/pull/438, I noticed that we do not support `B` or `BS`. 
As such, this PR adds support for it. I also improved our test script to be easier to run.
> [DynamoDB] Supporting bytes and bytes set

- integration_tests/postgres/main.go
- sources/postgres/adapter/adapter_test.go
- sources/postgres/adapter/converters.go
We are currently omitting the `Z` from the output and is not consistent with Debezium.
This PR ensures we are using the same layout.
> Aligning `TimeWithTimeZone` to Debezium

- sources/mongo/streaming.go
Whenever we commit offsets, let's log it - so we have a trail of what the offsets used to be
> Log offsets

- examples/dynamodb/service_account.tf
Tweaking the example service account script that has the ability to initiate a DynamoDB export to S3
> Tweak DynamoDB example permissions

- sources/mongo/message.go
- sources/mongo/message_test.go
This PR works to minimize the amount of marshalling and unmarshalling we need to do just to generate the JSON extended string for the primary key.
We are doing this by natively supporting and converting the most common data types and falling back to marshaling if we need to
> [MongoDB] Improve casting primary key efficiency

- lib/throttler/throttler.go
- lib/throttler/throttler_test.go
- sources/dynamodb/dynamodb.go
- sources/dynamodb/shard.go
- sources/dynamodb/stream.go
The limit is set to 20 for now; we can monitor lag time (added in https://github.com/artie-labs/reader/pull/452) and adjust the limit if needed.
> Throttle processing of dynamo shards to avoid cpu spikes

- lib/s3lib/s3lib.go
- sources/dynamodb/snapshot.go
- writers/writer.go
* Some JSON gzipped rows can be larger than 64 kb (which is the default buffer size), which caused this codepath to crash.
* Currently code is running dedupe at the end of every JSON file which is very expensive, instead, we should run it at the very end.
> [DynamoDB] Improve snapshot capabilities

- sources/dynamodb/snapshot.go
Right now, we're reading the entire `json.gz` file and then writing it.
DynamoDB chunks the files for 1.5M rows per file by default. However, if the row is really large - we're susceptible to OOM errors
> [DynamoDB] Avoid OOMing from snapshotting

- config/dynamodb.go
- lib/s3lib/s3lib.go
- sources/dynamodb/dynamodb.go
1. Increasing limit from 20 -> 30 (I'm increasing this because I'm seeing quite a bit of throttling happening in our logs)
2. Moving bucket name to be higher level, so if we do decide to use `specifiedFiles`, it's less repetitive
> [DynamoDB] Increase concurrency limit + refactor S3 bucket name

- config/dynamodb.go
- sources/dynamodb/dynamodb.go
Running at a limit of 30 is still too low as there could be idle shards that are still being processed [1]. And there may be more "active" shards that we should be able to process. 
However, these idle shards are taking up our throttler's quota. 
I think we might want to rethink the way we're handling throttling by throttling the rate of messages with a buffered channel as opposed to throttle concurrency (or maybe we need both ?)
For now, I've increased the default limit, allowed an override and added a TODO for us to come back to this.
----
[1] - We are still processing because the shard hasn't been closed yet, however there is no data
> [DynamoDB] Increase concurrency limit

- README.md
- config/mongodb.go
- sources/mongo/mongo.go
We need the ability to disable TLS so we can support DocumentDB.
> [MongoDB] Adding an option to disable TLS

- sources/mongo/change_event.go
- sources/mongo/change_event_test.go
- sources/mongo/streaming.go
[replace](https://www.mongodb.com/docs/manual/reference/change-events/replace/) is functionally the same as update, but separate action in MongoDB streams
> [MongoDB] Support replace

- config/config_test.go
- config/dynamodb.go
- sources/dynamodb/dynamodb.go
- sources/dynamodb/dynamodb_test.go
We can parse the AWS region from the ARN, so we don't need them to specify the region.
> Parse DynamoDB ARN

- config/mongodb.go
- lib/mongo/config.go
- lib/mongo/config_test.go
- lib/ptr/ptr.go
- sources/mongo/change_event.go
- sources/mongo/change_event_test.go
- sources/mongo/message.go
- sources/mongo/message_test.go
- sources/mongo/mongo.go
- sources/mongo/snapshot.go
- sources/mongo/streaming.go
- writers/transfer/writer_test.go
Refactoring our MongoDB client to support pre-image.
* Allowing no username / password to be specified
* Pulled building `opts` into a separate package and added tests
* Support `FullDocumentBeforeChange`
> [MongoDB] Clean up + support `FullDocumentBeforeChange`

- .github/workflows/gha-go-test.yaml
https://github.com/dominikh/go-tools/releases/tag/2024.1
> Bump staticcheck to `2024.1`

- config/mongodb.go
- sources/mongo/streaming.go
DocumentDB doesn't support it and will throw an error if it happens.
> Support disabling `SetFullDocumentBeforeChange`

- lib/dynamo/message.go
DynamoDB has an attribute called [NULL](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html#:~:text=Required%3A%20No-,NULL,-An%20attribute%20of) which does not map to any data type.
We shouldn't add this to the schema if there's no actual data type
> Skip empty fieldTypes

- lib/debezium/converters/decimal.go
- lib/debezium/converters/decimal_test.go
- lib/debezium/converters/money.go
Copy `decimalWithNewExponent` and `encodeDecimalWithScale` from transfer so that they can be removed from transfer.
Since `decimalWithNewExponent` is somewhat opinionated (it truncates extra digits rather rounding or returning an error) it makes more sense to have it reader where it is used so that we can decide which behavior is ideal.
> Move `encodeDecimalWithScale` from transfer

- .goreleaser.yaml
Fixes: 
> DEPRECATED:  snapshot.name_template  should not be used anymore, check https://goreleaser.com/deprecations#snapshotnametemplate for more info
> Change deprecated goreleaser property

- lib/mongo/change_event.go
Similar to https://github.com/artie-labs/reader/pull/461.
Sometimes the `fullDocumentBeforeChange` may be nil
> [MongoDB] Address edge case with `fullDocumentBeforeChange`

- config/postgres.go
- lib/postgres/table.go
- sources/postgres/adapter/adapter.go
Supporting the ability to specify primary keys, which would disable the automatic retrieval of primary keys
> [Postgres] Primary key override

- .github/CODEOWNERS
- go.mod
- go.sum
- integration_tests/mongo/main.go
- lib/mongo/message_test.go
> Upgrade Artie Transfer.

- go.mod
- go.sum
- lib/debezium/converters/decimal_test.go
- lib/debezium/converters/money_test.go
- lib/debezium/converters/time_test.go
- sources/postgres/adapter/adapter_test.go
> Upgrade Artie Reader + unbreak tests

- lib/mysql/schema/schema.go
- lib/mysql/schema/schema_test.go
> [MySQL] Adding all the LOB types + refactoring tests

- lib/debezium/converters/decimal.go
- lib/debezium/converters/decimal_test.go
- lib/debezium/converters/money.go
- lib/debezium/converters/money_test.go
We haven't seen `Warn if value scale is different from schema scale` in the logs in the past three weeks.
> Return error if value scale is different from schema scale

- lib/mysql/schema/convert.go
- lib/mysql/schema/convert_test.go
- lib/mysql/schema/schema.go
- sources/mysql/adapter/adapter.go
- sources/mysql/adapter/adapter_test.go
We previously treated `bit` as `bit(1)`. However, bit is actually `bit(M)`, where M can range from 1 to 64.
https://dev.mysql.com/doc/refman/8.4/en/bit-type.html
> [MySQL] Read MySQL bit size

- go.mod
- go.sum
- integration_tests/mongo/main.go
- lib/debezium/converters/time.go
- lib/debezium/converters/time_test.go
- lib/mongo/message_test.go
`ZonedTimestampConverter` was using the wrong layout and Transfer's converter was failing to parse.
We should also convert the values into UTC writing the layout out.
> Upgrade deps + fix `ZonedTimestampConverter`

- config/postgres.go
- config/postgres_test.go
- lib/rdbms/column/column.go
- lib/rdbms/column/column_test.go
- sources/postgres/adapter/adapter.go
Adding the ability to filter out columns that were not on the include list.
Following a similar pattern to [Debezium](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-column-include-list)
> [Postgres] Adding Column allowlist

- config/mssql.go
- config/mssql_test.go
- config/mysql.go
- config/mysql_test.go
- sources/mssql/adapter/adapter.go
- sources/mysql/adapter/adapter.go
> Column allowlist for MySQL and MSSQL

- config/dynamodb.go
- lib/dynamo/util.go
- lib/dynamo/util_test.go
- lib/s3lib/s3lib.go
- lib/s3lib/s3lib_test.go
- sources/dynamodb/dynamodb.go
- sources/dynamodb/snapshot/export.go
- sources/dynamodb/snapshot/snapshot.go
This PR adds the ability to support DDB export:
1. We will initiate an export (if it hasn't been initiated before)
2. Wait until export is done
3. Read and backfill the tables from the export
> [DynamoDB] Support backfills

- .github/workflows/gha-go-test.yaml
`make race` already runs tests, so we don't need to run tests a second time.
> github: run tests just once

- .github/workflows/gha-go-test.yaml
So that the duration of the GitHub actions steps are more predictable, otherwise the dependencies are installed in the next step.
> github: add step to install Go dependencies

- .github/workflows/gha-go-test.yaml
- .github/workflows/gha-integration-tests.yaml
- Makefile
- lib/mocks/generate.go
We're generating mocks (`FakeClient`) that we aren't using anywhere.
> github: stop generating unused mocks

- integration_tests/postgres/main.go
- lib/debezium/converters/decimal.go
- lib/debezium/converters/decimal_test.go
This behavior (returning nulls) is the same as Debezium.
> [postgres] Support numeric columns with "NaN" values

- lib/kafkalib/batch.go
With the goal of inlining `batched` in the next PR. Existing [tests](https://github.com/artie-labs/reader/blob/9082ca125337d65d86b0d783108e2f94e14df8c8/lib/kafkalib/batch_test.go#L9) ensure that this is functionally equivlelent.
> Reimplement `kafkalib.batched` using `slices.Chunk`

- sources/dynamodb/offsets/offsets.go
Found a scenario where a shard still existed after 2 days
> [DDB] Increase shard TTL

- lib/transfer/columns.go
- lib/transfer/columns_test.go
- sources/mysql/snapshot.go
- sources/postgres/adapter/adapter.go
- sources/postgres/adapter/adapter_test.go
- sources/postgres/snapshot.go
This is a continuation of https://github.com/artie-labs/reader/pull/563.
This PR adds the following changes:
* Moves the implementation of `BuildTransformerColumn` out into a shared package
* MySQL snapshot is now calling it
> Create table fast follow + enabling MySQL

- lib/mysql/schema/schema.go
This function is needed so that we can download the schema definition in the case where the table definition does not exist in the binlog.
> [MySQL] Get Create Table DDL

- lib/iterator/iterator.go
- lib/storage/persistedmap/persistedmap.go
- lib/storage/persistedmap/persistedmap_test.go
- sources/mongo/streaming.go
- sources/mysql/streaming/iterator.go
- writers/writer.go
This PR simplifies our implementation of `PersistedMap`. 
Before, we had an async go-routine that would save the contents of the persisted map every 15 seconds if it needed to be saved.
Now we are saving it whenever `Set` gets called, removing the go-routines and the need for mutexes.
> Simplifying PersistedMap

- writers/transfer/writer.go
- writers/transfer/writer_test.go
With this change https://github.com/artie-labs/reader/pull/563, we are now creating tables for tables that don't yet exist.
However, we missed adding the additional Artie generated columns such as `__artie_updated_at` which takes consideration from inspecting the `topicConfig`. This PR adds that capability.
> Add Artie generated columns

- lib/antlr/create_table.go
- lib/antlr/create_table_test.go
- lib/antlr/parse.go
- lib/debezium/transformer/light_transformer.go
- sources/mysql/streaming/ddl/table_adapter.go
- sources/mysql/streaming/dml.go
TIL that there's a discrepancy between `SHOW CREATE TABLE <table_name>` for different MySQL versions.
This PR does two things:
1. Adds validation to ensure all emitted rows must have partition keys set
2. Handle the ability to process primary key DDLs where the primary key is not specified inline with the column definition.
> [MySQL] Handling different flavors of `SHOW CREATE TABLE ...` with regards to PKs

- lib/debezium/transformer/light_transformer.go
- sources/mysql/streaming/ddl/ddl_test.go
- sources/mysql/streaming/ddl/table_adapter.go
- sources/mysql/streaming/dml.go
Moving the filter columns logic to `buildParsedColumns` so we can filter out columns at a higher level.
Once this PR is in, we'll have column exclusion supported.
> [MysQL] Moving filter columns logic

- lib/mysql/gtid.go
- lib/mysql/gtid_test.go
- sources/mysql/streaming/iterator.go
- sources/mysql/streaming/offset.go
A GTID in MySQL looks like:
```
GTID = source_id:transaction_id
For example: 3E11FA47-71CA-11E1-9E33-C80AA9429562:23
* source_id = the originating server ID.
* transaction_id = sequence number that goes up to 2^63-1 (int64)
```
A GTID Set could look like this:
```
GTID Set = source_id:transaction_id-transaction_id
For example: 3E11FA47-71CA-11E1-9E33-C80AA9429562:23-29
As well as
GTID Set = source_id:transaction_id-transaction_id,source_id1:transaction_id-transaction_id
```
As such, I've updated our PR to store the GTID set as opposed to the last known GTID.
This PR also adds a guardrail to ensure that we don't process GTIDs that have already been "seen" or "processed". Given that `transaction_id` is a sequence number. If the current `transaction_id` is less than our current position, we …
> [MySQL] Improving GTID offset management + dedupe

- lib/mysql/gtid.go
- lib/mysql/gtid_test.go
A MySQL instance that does not have GTID enabled may still emit `GTID Event`. The `GTID Set` in that case could be empty since we never tried to parse it.
That would then lead to a type assertion failure, which this is now accounting for.
> Additional GTID check

- lib/mysql/schema/convert.go
- lib/mysql/schema/convert_test.go
To account for the differences in returned data types from streaming and snapshot
> [MySQL] Extending `Binary` converter to handle string in addition to `[]bytes`

- lib/logger/logger.go
- sources/mysql/streaming/dml.go
- sources/mysql/streaming/iterator.go
Moving some logs that could be noisy into `.Debug` and then adding an ENV VAR called `READER_DEBUG` which can be used to toggle the debugging logs.
> Adding a DEBUG mode

- lib/antlr/create_table.go
- lib/antlr/create_table_test.go
- lib/antlr/drop_table_test.go
- lib/antlr/rename_table.go
- lib/antlr/rename_table_test.go
- lib/antlr/util.go
Being consistent with how we are extracting the table names for each DDL event.
> [DDL] Rename table and Copy table to use `getTableNameFromNode`

- lib/mysql/schema/schema.go
- sources/mysql/streaming/iterator.go
This way, we don't run into edge cases like subscribing to a DDL event where we don't have the table adapter, or run into situations like table rename or `CREATE TABLE LIKE`
> [MySQL] Retrieve all tables in a particular schema

- lib/antlr/create_table_test.go
- lib/antlr/parse.go
In MySQL, Materialized views are labelled as `BASE TABLES` in `SHOW FULL TABLES`. This PR improves our DDL library to filter them out.
> [DDL] Skipping mat tables

- integration_tests/mongo/main.go
- lib/mongo/message.go
We double nested `payload` for MongoDB messages
Once here: https://github.com/artie-labs/reader/blob/09aa180115417118b9c4d0a4d22ca3ed32912940/lib/kafkalib/writer.go#L89
Then the second time in the referenced PR.
> Fix MongoDB primary key

- integration_tests/mongo/main.go
- integration_tests/mssql/main.go
- integration_tests/mysql/main.go
- integration_tests/postgres/main.go
- integration_tests/utils/utils.go
- lib/debezium/transformer/transformer_test.go
- lib/kafkalib/message.go
- lib/kafkalib/message_test.go
- lib/kafkalib/writer.go
- sources/postgres/adapter/transformer_test.go
- writers/transfer/writer.go
- writers/writer_test.go
This PR improves upon 2 functionalities that we have
1. Building the Kafka message partition key
2. Centralizing Kafka topic name formation
On #1, this would prevent us from running into issues like this: https://github.com/artie-labs/reader/pull/629 by centralizing and testing how partition keys are generated.
> Improve `kafkalib/message.go`
